name: "ðŸ”„ Content Update"
description: "Use this template for straightforward updates to existing documentation"
title: "[CHALLENGE] - Update: Brief description"
labels: ["content-update"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # ðŸ”„ Content Update Order
        > **Executive Summary:**  
        > Make specific targeted changes to existing documentation to improve accuracy, clarity, or completeness.

  - type: input
    id: challenge_area
    attributes:
      label: "Challenge Area"
      description: "Choose one: AI Ready Challenge | AI Agent Challenge | AI Hub Challenge | General Documentation"
      placeholder: "e.g., AI Ready Challenge"
    validations:
      required: true

  - type: input
    id: files_to_update
    attributes:
      label: "File(s) to Update"
      description: "List the exact file paths (e.g., docs/ai-ready/step1.md)"
      placeholder: "e.g., docs/ai-ready/step1.md"
    validations:
      required: true

  - type: dropdown
    id: estimated_time
    attributes:
      label: "Estimated Time"
      options:
        - "â˜• Small (< 1 hour)"
        - "â˜•â˜• Medium (1-2 hours)"
        - "â˜•â˜•â˜• Large (2+ hours)"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "ðŸŸ¢ Low"
        - "ðŸŸ¡ Medium"
        - "ðŸŸ  High"
        - "ðŸ”´ Urgent"
    validations:
      required: true

  - type: input
    id: required_by_date
    attributes:
      label: "Required by Date"
      description: "When should this be completed by?"
      placeholder: "e.g., 2025-06-20"

  - type: textarea
    id: what_needs_updating
    attributes:
      label: "ðŸ” What Needs to Be Updated?"
      description: "Describe specifically what needs to be changed in the document(s)"
    validations:
      required: true

  - type: textarea
    id: proposed_changes
    attributes:
      label: "ðŸ“ Proposed Changes"
      description: "Describe the changes to be made, or provide draft content if available"

  - type: textarea
    id: success_criteria
    attributes:
      label: "âœ… Success Criteria"
      description: "How will we know the update is complete and correct?"
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2

  - type: input
    id: content_author
    attributes:
      label: "Content Author"
      description: "GitHub handle of the content author"
      placeholder: "@username"

  - type: dropdown
    id: reviewer_needed
    attributes:
      label: "Reviewer Needed"
      options:
        - "Technical"
        - "Documentation"
        - "Both"
        - "None"

  - type: checkboxes
    id: update_checklist
    attributes:
      label: "ðŸ“‹ Update Checklist"
      options:
        - label: "Content is technically accurate and up-to-date"
        - label: "Format follows existing documentation standards"
        - label: "Links have been verified"
        - label: "Changes match the specified requirements"
        - label: "Any new terminology is consistent with our shared glossary"

  - type: textarea
    id: update_progress
    attributes:
      label: "â© Update Progress"
      description: |
        Track update progress here. Example:
        | âœ… Stage | ðŸ“… Date | ðŸ‘¤ Completed By |
        |----------|----------|----------------|
        | â˜• Changes Made | 2025-06-10 | @username |
        | â˜•â˜• Review Complete | 2025-06-11 | @reviewer |
        | âœ“ Merged | 2025-06-12 | @maintainer |

  - type: textarea
    id: additional_notes
    attributes:
      label: "ðŸ“ Additional Notes"
      description: "Any additional context or notes"
